# Generated by Django 2.2.10 on 2020-05-30 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190630_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='discount_price',
        ),
        migrations.AlterField(
            model_name='address',
            name='zip',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('G', 'Groceries & Essentials'), ('FV', 'Fruits & Vegetables'), ('SP', 'Send Packages'), ('MF', 'Meat & Fish'), ('M', 'Medicines'), ('GL', 'Gifts & Lifestyle')], max_length=2),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.IntegerField(max_length=6),
        ),
    ]
